### ISSUE TITLE
Mention handout as similar project

### ISSUE THREAD

**Issue by pybokeh** [MarcSkovMadsen/awesome-streamlit#1]
https://github.com/danijar/handout

**Comment by MarcSkovMadsen** [comment]
Hi @pybokeh 

Thanks so much for reaching out. 

I did not know handout, but I tried it and liked it. It's really nice and fast. And I could maybe actually use it to generate static reports if I need them one day. But Streamlit is for creating highly interactive applications. It's a kind of React for Python. So I in order to keep the list focused I choose not to include it.

But thanks again for reaching out.

Marc
